<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Website Title</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            padding: 0;
        }

        header {
            text-align: center;
            padding: 10px;
            background-color: #f2f2f2;
        }

        nav {
            margin: 10px 0;
        }

        nav a {
            margin-right: 15px;
            text-decoration: none;
            color: #333;
        }

        section {
            margin: 20px 0;
        }

        footer {
            text-align: center;
            padding: 10px;
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>

    <header>
        <h1>Your Website</h1>
    </header>

    <nav>
        <a href="#">Home</a>
        <a href="#">About</a>
        <a href="#">Contact</a>
    </nav>

    <section>
        <h2>Welcome to Our Website</h2>
        <p>This is a sample section. You can customize it with your own content.</p>
    </section>

    <footer>
        <p>&copy; 2024 Your Website. All rights reserved.</p>
    </footer>

</body>
</html>
